### ISSUE TITLE
Navod z readme pre install.sh

### ISSUE THREAD

**Issue by lucorp** [LinuxOSsk/Shakal-NG#122]
Navod v README.md pre instalaciu cez install.sh skript nefunguje kvoli nefunkcnemu linku v Makefile. Chcelo by to spravit navod urceny pre novsie distra.

@mireq Vyuzivas na serveri nieco z install.sh?

**Comment by mireq** [comment]
Install.sh som použil na serveri dokopy raz ;) Teraz som to aktualizoval tak, aby to hádam fungovalo aj na novších ubuntu a debianoch.
