### ISSUE TITLE
Link na Ochranu osobnych udajov do paty/stale viditelneho miesta

### ISSUE THREAD

**Issue by lucorp** [LinuxOSsk/Shakal-NG#125]
Do paty by bolo vhodne umiestnit link na podstranku s ochranou osobnych udajov, nech sa znova neopakuje flame spred tyzdna. Takto zostane aj koza cela (splenenie klauzuly zakona o informovani o zachadzani s osobnymi udajmi) aj vlk syty (nebudeme zobrazovat zbytocny bordel uzivatelovi cez popup listu).

**Comment by mireq** [comment]
Podstránka s ochranou osobných údajov chýba? Je tam zabudnutý commit, alebo máme skúsiť pohľadať najaký generický text?

**Comment by lucorp** [comment]
zabudnuty file v commite. Fixnute commitom https://github.com/LinuxOSsk/Shakal-NG/commit/0c00e550eb630be4ffbd8e9ecf19f9508c5d8879
