### ISSUE TITLE
Sposob zobrazenia rodica komentu

### ISSUE THREAD

**Issue by lucorp** [LinuxOSsk/Shakal-NG#127]
Uz sa na to stazovalo viac ludi a niekedy ani ja nevidim na co reaguje komentator, specialne, ked je originalny comment o vysku okna a viac vzdialeny od reakcie.

Mozno nieco na sposob SMEcka, kde je piktogram a pri hoveri kurzorom sa zobrazi tooltip s predchadzajucim komentom?

![image](https://user-images.githubusercontent.com/4839225/85329153-427f6b00-b4d2-11ea-9e98-da0aa2aa52b8.png)

**Comment by lucorp** [comment]
Plati pre vsetky temy, alebo iba default?

**Comment by mireq** [comment]
Pridané
![komentar](https://user-images.githubusercontent.com/33599/96371739-8ffba400-1163-11eb-87ac-d6b162fbabf2.png)
