### ISSUE TITLE
/reklama na stranke

### ISSUE THREAD

**Issue by lucorp** [LinuxOSsk/Shakal-NG#129]
Mame verejne dostupnu adresu http://linuxos.sk/reklama/ kde su asi celkom neaktualne informacie. Co s tym? Mame vobec nejaku moznost v pripade objednavky pridat bez doprogramovavania takuto reklamu a su poskytnute kontaktne informacie platne?

**Comment by mireq** [comment]
Miesto pre reklamu môže byť problém keďže máme rôzne štýly a taktiež je otázdne či chceme reklamu a ak áno kto by mal spravovať financie a akým spôbom. Kým nevyriešime toto myslím, že stránka reklamy môže ísť preč.

**Comment by mireq** [comment]
Odstraňujem stránku reklama.
