### ISSUE TITLE
Zbytocne rozbijanie navstevnosti z hladiska SEO

### ISSUE THREAD

**Issue by lucorp** [LinuxOSsk/Shakal-NG#131]
Pri ssl a non-ssl verzii stranky si zbytocne rozbijame SEO a navzajom si sami sebe konkurujeme v SERP. Aky je dovod na subezne pouzivanie non-ssl a ssl?

![2020-07-07 09_48_33-Výkon vášho vlastníctva http___linuxos sk_ vo Vyhľadávaní za jún - stefan lucivj](https://user-images.githubusercontent.com/4839225/86741926-0bfc3100-c038-11ea-8569-cbce441950d3.png)
![2020-07-07 09_49_29-Výkon vášho vlastníctva https___linuxos sk_ vo Vyhľadávaní za jún - stefan luciv](https://user-images.githubusercontent.com/4839225/86741933-0c94c780-c038-11ea-8eed-a476d6324be2.png)

**Comment by mireq** [comment]
Hmm teoreticky by si nemali konkurovať kedže majú canonical URL nastavenú na https.

**Comment by lucorp** [comment]
skusim to pozriet este vo webmastertoolsoch. Ten percentualny pomer mi pride ale velmi vysoky na to aby to boli iba directy. Napisem ked zistim nieco viac.

**Comment by mireq** [comment]
Myslím, že už je to irelevantné, zapol som presmerovanie na https.

**Comment by lucorp** [comment]
ok, tym padom zatvaram.
