### ISSUE TITLE
Po registracii nechodi userom mail

### ISSUE THREAD

**Issue by lucorp** [LinuxOSsk/Shakal-NG#133]
![image](https://user-images.githubusercontent.com/4839225/90114771-7c8f1f80-dd53-11ea-83d7-0515766c247d.png)

**Comment by mireq** [comment]
Pozerám tu https://linuxos.sk/administracia/django_email_log/email/ a nejaké maily vyzerajú ako odoslané. Skúšal som si pokusne odoslať e-mail na gmail a došiel. Otázka je, nechodí to do spamu?

**Comment by bedna-KU** [comment]
Je to potvrdené, padá to do spamu https://github.com/LinuxOSsk/Shakal-NG/issues/133

**Comment by lucorp** [comment]
podla domain scanu su tam nejake problemy s DMARC a invalidnym hostnamom mail.linuxos.sk: [https://mxtoolbox.com/domain/linuxos.sk/](https://mxtoolbox.com/domain/linuxos.sk/)

![image](https://user-images.githubusercontent.com/4839225/90164796-1d9fc980-dd98-11ea-8650-25c0e3ad9225.png)

**Comment by mireq** [comment]
DMARC / DKIM / SPF som nastavil, chyby sú preč a dúfam, že som opravil hádzanie do spamu. Na teraz uzatváram, ak sa vyskytne nová chyba pls nový bugreport.
