### ISSUE TITLE
Nahrané video dať medzi tag VIDEO

### ISSUE THREAD

**Issue by bedna-KU** [LinuxOSsk/Shakal-NG#134]
Bolo by dobrré pre nahrané video dať možnosť prehrať ho priamo v prehliadači.

Toto ma fakt dosť sere.

Only YouTube mi príde ako sračka.

**Comment by mireq** [comment]
Ktorú službu integrovať?

**Comment by bedna-KU** [comment]
Aha, teraz som zistil, že aj lokálne súbory sa dajú uzatvárať medzi **video** tag. Ja že keď to neponúka kliknutie na ikonku video, tak je to zakázané.

**Comment by bedna-KU** [comment]
Tak vyzerá to, že lokálne video sa nikdy neprehrá, skúšal som niekoľko osvedčených formátov. Máš nejaký help?

**Comment by bedna-KU** [comment]
Skúsil som ho nahrať na KUweb a tam ide v pohode.

**Comment by bedna-KU** [comment]
Tak som zmenil tag na `<video width="800px" controls autoplay>` a je to OK.
