### ISSUE TITLE
Editovanie tém vo fóre nefunguje.

### ISSUE THREAD

**Issue by bedna-KU** [LinuxOSsk/Shakal-NG#136]
Keď kliknem, že chcem tému editovať, hodí ma do hlavnej stránky administrácie.

**Replikovanie problému:**
Stačí si skúsiť editovať hocijakú tému vo fóre.

**Comment by bedna-KU** [comment]
Trochu zmena, ak sú pri téme komentáre, hodí ma pri pokuse editovať tému do editácie komentárov.

**Comment by mireq** [comment]
Vpravo hore je odkaz na administráciu.
