### ISSUE TITLE
Neukazujú sa nové príspevky v blogoch

### ISSUE THREAD

**Issue by bedna-KU** [LinuxOSsk/Shakal-NG#140]
Čau Mirec, poprosím ťa o súrnejšiu opravu.

Dnes som zistil, že ak mi niekto napíše do blogu komentár tak mi nevypláva do "Najnovšie články a blogy" ako to bolo predtým.

**Comment by bedna-KU** [comment]
Som tento týždeň menej pri kompe, tak teraz som si není istý, či som tam symbol neprečítaného príspevku v blogu neprehliadol na telefóne, ale podľa mňa to blbne.

**Comment by bedna-KU** [comment]
Napísal som odpoveď v blogu a nevypláva hore v "Najnovšie články a blogy", tak tam predsa asi bug bude :)

**Comment by mireq** [comment]
Neviem, či je to bug. V tej sekcii sú najnovšie články / blogy, ale najnovšie ako najnovšie, nie, že majú najnovšie komentáre.

**Comment by bedna-KU** [comment]
OK, tak rozhodni sám či to nechať tak.

**Comment by mireq** [comment]
Keďže sú tam najnovšie uzatváram issue.
