### ISSUE TITLE
Pridať možnosť vkladania YT videí a img v správach

### ISSUE THREAD

**Issue by lucorp** [LinuxOSsk/Shakal-NG#63]
V správach by bolo dobré mať možnosť pridávania obrázkov a buď youtube videí, alebo priamo iframov do dlhého textu správy.

**Comment by mireq** [comment]
Obrázky - len titulný kvôli zdieľaniu, alebo kdekoľvek v texte ako v blogoch?

**Comment by lucorp** [comment]
Kdekolvek v texte, tak ako v blogoch.
