### ISSUE TITLE
Presunutie Shakala do LinuxOSsk organizácie

### ISSUE THREAD

**Issue by bedna-KU** [LinuxOSsk/Shakal-NG#70]
Možno by bolo zaujímavé presunúť Shakala do  LinuxOSsk organizácie pre pritiahnutie vývojárov. Stále tam budeš mať právo nastviť členom oprávnenia a byť správcom organizácie. Môžeme to prípadne spropagovať, keď som o Shakalovi písal, tak sa sem tam niekto ozval, možno keby dostal pozvánku tak by sa to viac rozbehlo. Rozhodnutie je samozrejme na tebe.

**Comment by mireq** [comment]
Zakladal som kvôli tomu organizáciu ... ale potom som to ďalej neriešil pretože by sa zmenili všetky URL adresy a na pôvodnom linku by zostalo 404. Pozriem ako sa to presúva.

**Comment by bedna-KU** [comment]
Ďakujem Mirec
