### ISSUE TITLE
Editovanie správ

### ISSUE THREAD

**Issue by bedna-KU** [LinuxOSsk/Shakal-NG#76]
Pridal som pre Maroš K práva pre editovanie správ, ale nefunguje to. Skúsil som vytvoriť aj nového testovacie užívatelia a výsledok rovnaký.

**Comment by mireq** [comment]
Vyriešim najskôr #77

**Comment by mireq** [comment]
Skúšal som editáciu správ pod iným užívateľom a mne funguje (viď screenshoty).

Skús ešte raz, či to blbne a skús popísať presný postup.

![prihlasenie](https://cloud.githubusercontent.com/assets/33599/13048072/af39e934-d3e3-11e5-81f2-117f17c0956e.png)
![prihlasenie_2](https://cloud.githubusercontent.com/assets/33599/13048076/b24ca8be-d3e3-11e5-8ca8-af09653d4d4f.png)

**Comment by bedna-KU** [comment]
Funguje, dík.
