### ISSUE TITLE
podpora animovanych gif-ov

### ISSUE THREAD

**Issue by kormidelnik** [LinuxOSsk/Shakal-NG#80]
podpora animovanych gif-ov v avataroch

**Comment by mireq** [comment]
Premýšľam nad tým, ale neviem, či je to dobrý nápad.

**Comment by bedna-KU** [comment]
Ja tiež moc niesom za blikajúci portál :)

**Comment by lucorp** [comment]
asi to nie je uplne idealne, specialne pri dlhych diskusiach.

**Comment by mireq** [comment]
OK, prediskutovali sme to, tiež nie som moc fanúšikov animovaných avatarov, sú s tým aj technické problémy pri zmene veľkosti (nedá sa aplikovať antialiasing), aj to môže byť pomalé na mobiloch, takže zatváram túto funkciu ako momentálne "wontfix".
