### ISSUE TITLE
Prepínanie tém

### ISSUE THREAD

**Issue by bedna-KU** [LinuxOSsk/Shakal-NG#88]
Zišlo by sa hodiť na web zoznam tém, kde by som si vybral z existujúcich tém, napr. &lt;select&gt; a &lt;button&gt; Zmeniť.

**Comment by mireq** [comment]
Vieš to prsnejšie špecifikovať?

**Comment by bedna-KU** [comment]
Ako si robil témy TurboPascal, Ponies ... žeby bolo niekde klikátko na ich prepínanie.

**Comment by mireq** [comment]
Povedal by som, že je to hotové - http://linuxos.sk/sablony/
