### ISSUE TITLE
Bug: Long article headings break CSS style

### ISSUE THREAD

**Issue by dumblob** [LinuxOSsk/Shakal-NG#90]
It seems, the article itself (including it's main heading) should be moved downwards in case the blue "path menu" (e.g. "Home" -> "Forum" -> "Komunita") is floating on the next line.

![2016-11-30-155131_1680x1050 0 0_imlib2_grab](https://cloud.githubusercontent.com/assets/2451044/20757210/aef451f6-b715-11e6-81e7-b845f439085c.png)

**Comment by lucorp** [comment]
Replikacia: Firefox 61.0.1 na ubuntu
