### ISSUE TITLE
Přesměrování stránky http na https

### ISSUE THREAD

**Issue by CoolmanCZ** [LinuxOSsk/Shakal-NG#91]
To vážně nejde udělat 301 z http na https?

Pokud zadám "http://www.linuxos.sk" dostanu "403 Forbidden nginx/1.6.2", protože to nepřesměrujete na https.

**Comment by mireq** [comment]
Uvedená adresa mi funguje s HTTP aj s HTTPS. Aký prehliadač vyhadzuje 403 s akými nastaveniami?

**Comment by CoolmanCZ** [comment]
Včera jsem to několikrát zkoušel na Fedora 24, Firefox 50.0.1.0 a nešlo to. Dnes to ale funguje.

**Comment by CoolmanCZ** [comment]
Dnes se mě opět objevila hláška "403 Forbidden nginx/1.6.2".

OS: Ubuntu 14.04 LTS, Firefox 50.1.0, bez proxy

**Comment by CoolmanCZ** [comment]
Tak to vypadá, že už to je opraveno
