### ISSUE TITLE
Zobrazenie novej ankety na nejakom viditeľnom mieste

### ISSUE THREAD

**Issue by bedna-KU** [LinuxOSsk/Shakal-NG#94]
Anketa sa zobrazje prakticky na konci stránky a málokto si ju všimne pokiaľ nezroluje úplne dole, dola by sa spraviť na vrchu stránky nejaká notifikácia?

**Comment by bedna-KU** [comment]
Inak by stačilo aby to vyplávalo medzi "Najnovšie články a blogy"

**Comment by mireq** [comment]
Hmm neviem, či by nebolo vhodnejšie, keby som dal anketu niekde na vyššie miesto v pravom stĺpci.

**Comment by bedna-KU** [comment]
OK, aj to je možnosť
