### ISSUE TITLE
preklep v ikonke Google+ (Goolge+)

### ISSUE THREAD

**Issue by jarole** [LinuxOSsk/Shakal-NG#95]
![goolge](https://user-images.githubusercontent.com/38654035/40002256-6cc69600-5790-11e8-91ef-4fb10b2a09cf.png)

Ikonka na google+ ma preklep GOOLGE+
pozdravujem a prajem vsetko dobre.

**Comment by mireq** [comment]
Opravené, vďaka za nahlásenie ;)
